name: build_and_test

on:
  push:
    branches:
      - main 
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: humble, ROS_REPO: ros }
    env:
      UPSTREAM_WORKSPACE: .ci.rosinstall
      # Source the setup file because the test depends on packages in the workspace
      BEFORE_RUN_TARGET_TEST_EMBED: "ici_with_unset_variables source /root/target_ws/install/setup.bash"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}